#!/bin/bash

sudo pkg install -y net/py-novaclient
sudo pkg install -y patch
sudo pkg install -y scons
sudo pkg install -y flex
sudo pkg install -y bison
sudo pkg install -y vim
sudo pkg install -y unzip
sudo pkg install -y autoconf
sudo pkg install -y automake
sudo pkg install -y libtool
sudo pkg install -y curl
sudo pkg install -y screen
sudo pkg install -y debhelper
sudo pkg install -y gmake
sudo pkg install -y libxml2
sudo pkg install -y libxslt
sudo pkg install -y expat
sudo pkg install -y gettext
sudo pkg install -y gcc47
sudo pkg install -y python2
sudo pkg install -y libevent2
sudo pkg install -y libvirt
sudo pkg install -y devel/py-lxml
sudo pkg install -y databases/py-redis
sudo pkg install -y apache-ant
sudo pkg install -y java/openjdk7
sudo pkg install -y log4j
sudo pkg install -y devel/pkgconf
sudo ln -s /usr/local/bin/gcc47 /usr/local/bin/gcc
sudo ln -s /usr/local/bin/g++47 /usr/local/bin/g++
